/** 方案甲指令名（提示词只教这些；解析另认旧方括号格式） */
export const WxCmd = {
  busy: '忙碌',
  redPacket: '红包',
  transfer: '转账',
  openRedPacket: '拆红包',
  acceptTransfer: '收转账',
  returnTransfer: '退转账',
  voiceCall: '语音通话',
  location: '发位置',
  image: '发图',
  sticker: '表情包',
  voice: '语音',
  quote: '引用',
  setAvatar: '换头像',
  setCover: '换背景',
  restoreAvatar: '恢复头像',
  restoreCover: '恢复背景',
  publishMoment: '发朋友圈',
  pinMoment: '置顶朋友圈',
  unpinMoment: '取消置顶朋友圈',
  setNick: '改昵称',
  setSig: '改签名',
  setProfile: '改资料',
  musicAccept: '共听接受',
  musicDecline: '共听拒绝',
  musicInvite: '共听邀请',
  musicPlay: '点歌',
  musicNext: '切下一首',
  musicPrev: '切上一首',
  musicSeek: '跳进度',
  takeout: '外卖',
  forwardOpen: '转发记录',
  forwardClose: '结束转发记录',
  pulseDmOpen: '微博私信截图',
  pulseDmClose: '结束微博私信截图',
  pulseFollowOpen: '微博关注',
  pulseFollowClose: '结束微博关注',
  pulseCommentOpen: '微博评论',
  pulseCommentClose: '结束微博评论',
  recall: '撤回',
} as const

export type WxCmdName = (typeof WxCmd)[keyof typeof WxCmd]
