/**
 * 从 Mixamo 动作提取「相对绑定姿」局部旋转 delta，供混元姿势库学习。
 * node --import tsx scripts/extract-mixamo-deltas.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import * as THREE from 'three'
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader.js'
import { buildCoreBoneMap, MIXAMO_CORE, type MixamoCore } from '../src/phone/apps/homeBuild/avatarBoneCore.ts'

globalThis.window = {
  URL: { createObjectURL: () => 'blob:n' },
  innerWidth: 1920,
  innerHeight: 1080,
} as Window & typeof globalThis
globalThis.document = {
  createElementNS(_ns: string, tag: string) {
    const el = { style: {}, setAttribute() {}, onload: null as (() => void) | null }
    if (tag === 'img') {
      Object.defineProperty(el, 'src', {
        set() {
          queueMicrotask(() => el.onload?.())
        },
        get() {
          return ''
        },
      })
    }
    return el as unknown as HTMLElement
  },
} as Document

THREE.ImageLoader.prototype.load = function (_u, onLoad) {
  onLoad?.({ width: 1, height: 1 } as unknown as HTMLImageElement)
  return { addEventListener() {}, removeEventListener() {} } as unknown as HTMLImageElement
}
THREE.TextureLoader.prototype.load = function (_u, onLoad) {
  const tex = new THREE.Texture()
  tex.image = { width: 1, height: 1 }
  onLoad?.(tex)
  return tex
}

const root = path.resolve(import.meta.dirname, '..')
const outPath = path.join(root, 'src/phone/apps/homeBuild/hunyuanPoseDeltas.generated.ts')

function loadFbx(filePath: string) {
  const buf = fs.readFileSync(filePath)
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
  return new FBXLoader().parse(ab, path.basename(filePath)) as THREE.Group
}

function collectBones(group: THREE.Object3D): THREE.Bone[] {
  const bones: THREE.Bone[] = []
  group.traverse((o) => {
    if (o instanceof THREE.Bone) bones.push(o)
  })
  return bones
}

function quatArr(q: THREE.Quaternion): [number, number, number, number] {
  return [+q.x.toFixed(5), +q.y.toFixed(5), +q.z.toFixed(5), +q.w.toFixed(5)]
}

function eulerDeg(q: THREE.Quaternion): [number, number, number] {
  const e = new THREE.Euler().setFromQuaternion(q, 'XYZ')
  return [
    +((e.x * 180) / Math.PI).toFixed(1),
    +((e.y * 180) / Math.PI).toFixed(1),
    +((e.z * 180) / Math.PI).toFixed(1),
  ]
}

function extractDeltas(
  group: THREE.Group,
  sampleTime: number | 'end',
): Record<string, [number, number, number, number]> {
  const bones = collectBones(group)
  const core = buildCoreBoneMap(bones)
  // bind
  for (const b of bones) {
    // restore from current - use skeleton if any
  }
  const skin = (() => {
    let s: THREE.SkinnedMesh | null = null
    group.traverse((o) => {
      if (o instanceof THREE.SkinnedMesh && o.skeleton) s = o
    })
    return s
  })()
  if (skin?.skeleton) skin.skeleton.pose()
  group.updateMatrixWorld(true)

  const bindLocal = new Map<MixamoCore, THREE.Quaternion>()
  for (const [c, bone] of core) bindLocal.set(c, bone.quaternion.clone())

  const clip = group.animations[0]
  if (!clip) return {}

  const mixer = new THREE.AnimationMixer(group)
  const action = mixer.clipAction(clip)
  action.play()
  const t =
    sampleTime === 'end' ? Math.max(0, clip.duration - 1e-4) : Math.min(sampleTime, clip.duration)
  mixer.setTime(t)
  group.updateMatrixWorld(true)

  const out: Record<string, [number, number, number, number]> = {}
  const _inv = new THREE.Quaternion()
  const _delta = new THREE.Quaternion()

  for (const [c, bone] of core) {
    const bind = bindLocal.get(c)
    if (!bind) continue
    _delta.copy(_inv.copy(bind).invert()).multiply(bone.quaternion)
    // normalize sign
    if (_delta.w < 0) _delta.set(-_delta.x, -_delta.y, -_delta.z, -_delta.w)
    const deg = (_delta.angleTo(new THREE.Quaternion()) * 180) / Math.PI
    if (deg < 0.5) continue
    out[c] = quatArr(_delta)
    console.log(
      `  ${c.padEnd(16)} deltaDeg=${deg.toFixed(1).padStart(5)} euler≈${JSON.stringify(eulerDeg(_delta))}`,
    )
  }

  mixer.stopAllAction()
  return out
}

const clips: Array<{ id: string; file: string; sample: number | 'end' }> = [
  { id: 'picked-up', file: 'picked-up.fbx', sample: 'end' },
  { id: 'fall-air', file: 'fall-air.fbx', sample: 0.35 },
  { id: 'fall-land', file: 'fall-land.fbx', sample: 'end' },
]

const library: Record<string, Record<string, [number, number, number, number]>> = {}

for (const entry of clips) {
  const filePath = path.join(root, 'public', 'home-animations', entry.file)
  console.log(`\n=== ${entry.id} (${entry.file}) ===`)
  if (!fs.existsSync(filePath)) {
    console.warn('missing', filePath)
    continue
  }
  const group = loadFbx(filePath)
  library[entry.id] = extractDeltas(group, entry.sample)
}

const ts = `/* Auto-generated by scripts/extract-mixamo-deltas.ts — Mixamo local rot deltas (bind^{-1} * pose) */
export type PoseDeltaQuat = readonly [number, number, number, number]
export type HunyuanPoseId = 'picked-up' | 'fall-air' | 'fall-land'

export const MIXAMO_LEARNED_DELTAS: Record<HunyuanPoseId, Partial<Record<string, PoseDeltaQuat>>> = ${JSON.stringify(library, null, 2)} as const
`

fs.writeFileSync(outPath, ts, 'utf8')
console.log('\nWrote', outPath)
