import type { BubbleSideDraft, LookWorkshopDraft, SpecialCardDraft } from './types'
import {
  defaultBubbleBadge,
  defaultBubbleShadow,
  defaultGradientStops,
} from '../wechat/bubbleBadge'

const softShadow = '0 2px 10px rgba(0,0,0,0.06)'

function side(bg: string, text: string): BubbleSideDraft {
  return {
    bg,
    bgGradient: '',
    useGradient: false,
    gradientMode: 'off',
    gradientAngleDeg: 135,
    gradientStops: defaultGradientStops(),
    glassEnabled: false,
    glassBlurPx: 16,
    glassSaturatePct: 140,
    glassEdgeBlurPx: 0,
    bgImage: '',
    bgImageBlurPx: 0,
    text,
    fontSizePx: 16,
    fontWeight: 400,
    lineHeight: 1.4,
    padT: 10,
    padR: 14,
    padB: 10,
    padL: 14,
    radius: 18,
    borderColor: 'rgba(0,0,0,0.06)',
    borderWidth: 0,
    shadow: softShadow,
    shadowDraft: defaultBubbleShadow(),
    showTail: false,
    tailCluster: 'first',
    tailAnchor: 'side',
    tailYMode: 'pct',
    tailOffsetYPct: 28,
    tailOffsetXPct: 0,
    tailOffsetXPx: 0,
    tailLengthPx: 6,
    tailAngleDeg: 55,
    tailRoundPx: 0,
    tailTiltDeg: 0,
    tailSurfaceMode: 'follow',
    tailBg: bg,
    tailGradientMode: 'off',
    tailGradientAngleDeg: 135,
    tailGradientStops: defaultGradientStops(),
    tailBgGradient: '',
    tailGlassEnabled: false,
    tailGlassBlurPx: 16,
    tailGlassSaturatePct: 140,
    maxWidthPct: 72,
    minWidthPx: 0,
    font: null,
    edgeStickers: [],
    frame: null,
    avatarStickers: [],
    badge: defaultBubbleBadge(),
    showAvatar: true,
    avatarCluster: 'first',
    avatarRadiusPx: 20,
    avatarBorderColor: 'rgba(0,0,0,0.08)',
    avatarBorderWidth: 0,
    avatarEdgeInsetPx: 24,
    avatarSizePx: 40,
    avatarPlaceholderColor: '#D4D4D4',
    avatarRotateDeg: 0,
    avatarBubbleYPct: 0,
  }
}

function special(accent: string): SpecialCardDraft {
  return {
    followBubble: true,
    bg: '#ffffff',
    borderColor: 'rgba(0,0,0,0.08)',
    borderWidth: 1,
    radius: 14,
    shadow: softShadow,
    accent,
    titleColor: '#191919',
    mutedColor: '#8e8e8e',
    amountColor: '#0f172a',
  }
}

export function createDefaultLookWorkshopDraft(): LookWorkshopDraft {
  return {
    version: 1,
    meta: {
      name: '外观工坊皮肤',
      description: '在外观工坊中编辑，导出后到「微信 → 外观 → 聊天气泡」上传',
      author: '',
    },
    gapSameSpeakerPx: 4,
    gapDifferentSpeakerPx: 12,
    msgAreaPadX: 0,
    msgAreaPadY: 12,
    other: { ...side('#ffffff', '#191919'), avatarPlaceholderColor: '#D4D4D4' },
    self: { ...side('#EDEDED', '#191919'), avatarPlaceholderColor: '#E5E5E5' },
    voice: special('#8d8d8d'),
    transfer: special('#B8D4C8'),
    redPacket: special('#D4AF37'),
    location: special('#D4AF37'),
    voiceCall: special('#191919'),
    favorite: special('#191919'),
    listenTogether: special('#57534e'),
    header: {
      heightPx: 48,
      bg: 'rgba(255,255,255,0.92)',
      bgMode: 'color',
      bgImage: '',
      bgImageBlurPx: 0,
      bgOverlayColor: '#ffffff',
      bgOverlayOpacity: 0,
      useBlur: true,
      blurPx: 16,
      textColor: '#191919',
      mutedColor: '#8e8e8e',
      borderColor: 'rgba(0,0,0,0.06)',
      showSubtitle: true,
      subtitleText: '对方正在输入…',
      titleSizePx: 15,
      titleWeight: 600,
      titleFont: null,
      subtitleFont: null,
      showTitleAvatar: false,
      titleAvatarSizePx: 28,
      titleAvatarRadiusPx: 14,
      titleAvatarPlacement: 'beside',
      btnColor: '',
      backBtn: {
        sizePx: 36,
        pos: { free: false, xPct: 7, yPct: 50 },
        iconDataUrl: '',
        iconSizePx: 20,
        iconRadiusPx: 0,
      },
      moreBtn: {
        sizePx: 36,
        pos: { free: false, xPct: 93, yPct: 50 },
        iconDataUrl: '',
        iconSizePx: 22,
        iconRadiusPx: 0,
      },
      timeBtn: {
        sizePx: 36,
        side: 'left',
        pos: { free: false, xPct: 18, yPct: 50 },
        iconDataUrl: '',
        iconSizePx: 18,
        iconRadiusPx: 0,
      },
      psycheBtn: {
        sizePx: 36,
        side: 'right',
        pos: { free: false, xPct: 82, yPct: 50 },
        iconDataUrl: '',
        iconSizePx: 20,
        iconRadiusPx: 0,
      },
      titleAvatarPos: { free: false, xPct: 36, yPct: 40 },
      titlePos: { free: false, xPct: 50, yPct: 40 },
      subtitlePos: { free: false, xPct: 50, yPct: 68 },
    },
    input: {
      barBg: 'rgba(255,255,255,0.94)',
      barBgImage: '',
      barBgImageBlurPx: 0,
      barBgOverlayColor: '#ffffff',
      barBgOverlayOpacity: 0,
      barBorder: 'rgba(0,0,0,0.06)',
      useBlur: true,
      blurPx: 14,
      shellBg: '#ffffff',
      shellBorder: '#e5e5e5',
      shellRadius: 18,
      textColor: '#191919',
      placeholderColor: '#8E8E93',
      btnColor: '#191919',
      padY: 8,
      btnIconSyncStyle: false,
      btnIcons: {
        voice: { dataUrl: '', sizePx: 22, radiusPx: 0 },
        keyboard: { dataUrl: '', sizePx: 22, radiusPx: 0 },
        emoji: { dataUrl: '', sizePx: 22, radiusPx: 0 },
        plus: { dataUrl: '', sizePx: 22, radiusPx: 0 },
        send: { dataUrl: '', sizePx: 22, radiusPx: 0 },
      },
    },
    timestamp: {
      bg: 'rgba(0,0,0,0.04)',
      textColor: '#999999',
      /** 胶囊感：时间戳高度约 20px，半径 ≥10 即近似满圆角 */
      radius: 12,
      padX: 12,
      padY: 4,
      font: null,
    },
    advanced: {
      roomBg: '#EDEDED',
      roomBgImage: '',
      globalBlurPx: 0,
      shadowStrength: 1,
    },
  }
}
