import { GRID_CELL_METERS } from './defaults'
import { distPointToSegment, floorPlanBounds, wallLength } from './floorPlanGeometry'
import type { DoorWindowOpening, FloorLevel, RoomZone, Vec2, WallSegment } from './types'

type GridCell = { gx: number; gz: number }

const EXTERIOR_PAD = 2
/** 网格单边上限，防止异常户型导致主线程卡死 */
const MAX_GRID_AXIS = 56
const MAX_GRID_CELLS = 3200

function cellKey(gx: number, gz: number): string {
  return `${gx},${gz}`
}

function isDoorGapOnWall(
  wall: WallSegment,
  openings: DoorWindowOpening[],
  p: Vec2,
): boolean {
  const len = wallLength(wall)
  if (len < 0.01) return false
  const hit = distPointToSegment(p, wall.a, wall.b)
  if (hit.dist > wall.thickness / 2 + 0.35) return false
  for (const op of openings) {
    if (op.wallId !== wall.id || op.kind !== 'door') continue
    const along = hit.t * len
    const center = op.t * len
    if (Math.abs(along - center) <= op.width / 2 + 0.15) return true
  }
  return false
}

function isBlockedByWalls(
  p: Vec2,
  walls: WallSegment[],
  openings: DoorWindowOpening[],
): boolean {
  for (const wall of walls) {
    const hit = distPointToSegment(p, wall.a, wall.b)
    if (hit.dist > wall.thickness / 2 + 0.35) continue
    if (isDoorGapOnWall(wall, openings, p)) continue
    return true
  }
  return false
}

function floodExterior(
  blocked: Set<string>,
  minGx: number,
  minGz: number,
  maxGx: number,
  maxGz: number,
): Set<string> {
  const exterior = new Set<string>()
  const queue: GridCell[] = []

  const trySeed = (gx: number, gz: number) => {
    const key = cellKey(gx, gz)
    if (blocked.has(key) || exterior.has(key)) return
    exterior.add(key)
    queue.push({ gx, gz })
  }

  for (let gx = minGx; gx <= maxGx; gx++) {
    trySeed(gx, minGz)
    trySeed(gx, maxGz)
  }
  for (let gz = minGz; gz <= maxGz; gz++) {
    trySeed(minGx, gz)
    trySeed(maxGx, gz)
  }

  while (queue.length) {
    const { gx, gz } = queue.pop()!
    for (const [dx, dz] of [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ] as const) {
      const nx = gx + dx
      const nz = gz + dz
      const key = cellKey(nx, nz)
      if (blocked.has(key) || exterior.has(key)) continue
      exterior.add(key)
      queue.push({ gx: nx, gz: nz })
    }
  }

  return exterior
}

function groupInteriorCells(cells: GridCell[]): GridCell[][] {
  const set = new Set(cells.map((c) => cellKey(c.gx, c.gz)))
  const groups: GridCell[][] = []
  const visited = new Set<string>()

  for (const cell of cells) {
    const startKey = cellKey(cell.gx, cell.gz)
    if (visited.has(startKey)) continue
    const group: GridCell[] = []
    const stack = [cell]
    visited.add(startKey)
    while (stack.length) {
      const cur = stack.pop()!
      group.push(cur)
      for (const [dx, dz] of [
        [1, 0],
        [-1, 0],
        [0, 1],
        [0, -1],
      ] as const) {
        const key = cellKey(cur.gx + dx, cur.gz + dz)
        if (!set.has(key) || visited.has(key)) continue
        visited.add(key)
        stack.push({ gx: cur.gx + dx, gz: cur.gz + dz })
      }
    }
    groups.push(group)
  }
  return groups
}

function tilesToRect(tiles: GridCell[]): RoomZone['rect'] {
  const xs = tiles.map((t) => t.gx)
  const zs = tiles.map((t) => t.gz)
  const minX = Math.min(...xs)
  const minZ = Math.min(...zs)
  const maxX = Math.max(...xs) + GRID_CELL_METERS
  const maxZ = Math.max(...zs) + GRID_CELL_METERS
  return { x: minX, z: minZ, w: maxX - minX, h: maxZ - minZ }
}

function manualOccupiedCells(manualRooms: RoomZone[]): Set<string> {
  const occupied = new Set<string>()
  for (const room of manualRooms) {
    if (room.tiles?.length) {
      for (const t of room.tiles) occupied.add(cellKey(t.x, t.z))
      continue
    }
    const minGx = Math.floor(room.rect.x)
    const minGz = Math.floor(room.rect.z)
    const maxGx = Math.ceil(room.rect.x + room.rect.w) - 1
    const maxGz = Math.ceil(room.rect.z + room.rect.h) - 1
    for (let gx = minGx; gx <= maxGx; gx++) {
      for (let gz = minGz; gz <= maxGz; gz++) {
        const cx = gx + 0.5
        const cz = gz + 0.5
        if (
          cx >= room.rect.x &&
          cx <= room.rect.x + room.rect.w &&
          cz >= room.rect.z &&
          cz <= room.rect.z + room.rect.h
        ) {
          occupied.add(cellKey(gx, gz))
        }
      }
    }
  }
  return occupied
}

export function detectEnclosedFloorTiles(
  floor: Pick<FloorLevel, 'walls' | 'openings' | 'rooms'>,
): GridCell[][] {
  if (!floor.walls.length) return []

  const manual = floor.rooms?.filter((r) => !r.autoGenerated) ?? []
  const manualCells = manualOccupiedCells(manual)

  const bounds = floorPlanBounds(floor as FloorLevel)
  let minGx = Math.floor(bounds.minX) - EXTERIOR_PAD
  let minGz = Math.floor(bounds.minZ) - EXTERIOR_PAD
  let maxGx = Math.ceil(bounds.maxX) + EXTERIOR_PAD
  let maxGz = Math.ceil(bounds.maxZ) + EXTERIOR_PAD

  const spanX = maxGx - minGx + 1
  const spanZ = maxGz - minGz + 1
  if (spanX > MAX_GRID_AXIS || spanZ > MAX_GRID_AXIS || spanX * spanZ > MAX_GRID_CELLS) {
    return []
  }

  const blocked = new Set<string>()
  for (let gx = minGx; gx <= maxGx; gx++) {
    for (let gz = minGz; gz <= maxGz; gz++) {
      const center = { x: gx + 0.5, z: gz + 0.5 }
      if (isBlockedByWalls(center, floor.walls, floor.openings)) {
        blocked.add(cellKey(gx, gz))
      }
    }
  }

  const exterior = floodExterior(blocked, minGx, minGz, maxGx, maxGz)
  const interior: GridCell[] = []
  for (let gx = minGx; gx <= maxGx; gx++) {
    for (let gz = minGz; gz <= maxGz; gz++) {
      const key = cellKey(gx, gz)
      if (!blocked.has(key) && !exterior.has(key) && !manualCells.has(key)) interior.push({ gx, gz })
    }
  }

  return groupInteriorCells(interior).filter((g) => g.length > 0)
}

export function pointInRoomTiles(p: Vec2, room: RoomZone): boolean {
  if (room.tiles?.length) {
    const gx = Math.floor(p.x)
    const gz = Math.floor(p.z)
    return room.tiles.some((t) => t.x === gx && t.z === gz)
  }
  const r = room.rect
  return p.x >= r.x && p.x <= r.x + r.w && p.z >= r.z && p.z <= r.z + r.h
}

export function syncAutoFloorRooms(
  floor: FloorLevel,
  createId: () => string,
): RoomZone[] {
  const manual = floor.rooms.filter((r) => !r.autoGenerated)
  const prevAuto = floor.rooms.filter((r) => r.autoGenerated)
  const prevByRect = new Map<string, RoomZone>()

  for (const room of prevAuto) {
    const { x, z, w, h } = room.rect
    prevByRect.set(`${x.toFixed(2)},${z.toFixed(2)},${w.toFixed(2)},${h.toFixed(2)}`, room)
  }

  const regions = detectEnclosedFloorTiles(floor)
  const autoRooms: RoomZone[] = regions.map((tiles, index) => {
    const rect = tilesToRect(tiles)
    const rectKey = `${rect.x.toFixed(2)},${rect.z.toFixed(2)},${rect.w.toFixed(2)},${rect.h.toFixed(2)}`
    const preserved = prevByRect.get(rectKey)
    return {
      id: preserved?.id ?? createId(),
      name: preserved?.name ?? `区域${index + 1}`,
      type: preserved?.type ?? 'other',
      rect,
      autoGenerated: true,
      floorMaterialId: preserved?.floorMaterialId ?? 'floor-wood-oak',
      wallMaterialId: preserved?.wallMaterialId ?? 'wall-white',
    }
  })

  return [...manual, ...autoRooms]
}
