import type { FloorLevel, HomeBuildDraft, MaterialSwatch } from './types'
import { WALL_HEIGHT } from './sceneConstants'

export const GRID_CELL_METERS = 1

/** 户型平面可建造网格（边长，单位格=1m） */
export const PLAN_GRID_DEFAULT = 18
export const PLAN_GRID_MIN = 14
export const PLAN_GRID_MAX = 40
export const PLAN_GRID_STEP = 4

export function clampPlanGridSize(n: unknown): number {
  const v = typeof n === 'number' && Number.isFinite(n) ? Math.round(n) : PLAN_GRID_DEFAULT
  const stepped = PLAN_GRID_MIN + Math.round((v - PLAN_GRID_MIN) / PLAN_GRID_STEP) * PLAN_GRID_STEP
  return Math.max(PLAN_GRID_MIN, Math.min(PLAN_GRID_MAX, stepped))
}

export function uid(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`
}

export function createDefaultFloor(label = '1F'): FloorLevel {
  return {
    id: uid('floor'),
    label,
    walls: [
      { id: uid('wall'), a: { x: 0, z: 0 }, b: { x: 8, z: 0 }, thickness: 0.2 },
      { id: uid('wall'), a: { x: 8, z: 0 }, b: { x: 8, z: 6 }, thickness: 0.2 },
      { id: uid('wall'), a: { x: 8, z: 6 }, b: { x: 0, z: 6 }, thickness: 0.2 },
      { id: uid('wall'), a: { x: 0, z: 6 }, b: { x: 0, z: 0 }, thickness: 0.2 },
    ],
    rooms: [
      {
        id: uid('room'),
        name: '客厅',
        type: 'living',
        rect: { x: 0.2, z: 0.2, w: 7.6, h: 5.6 },
        autoGenerated: false,
        floorMaterialId: 'floor-wood-oak',
        wallMaterialId: 'wall-white',
      },
    ],
    openings: [],
    floorTileMaterials: [],
    wallSegmentMaterials: [],
    ceilingHoles: [],
    wallHeight: WALL_HEIGHT,
  }
}

export function createDefaultHomeDraft(characterId: string): HomeBuildDraft {
  const floor = createDefaultFloor('1F')
  return {
    format: 'lumi-home-build-draft',
    version: 1,
    characterId,
    updatedAt: Date.now(),
    floors: [floor],
    furniture: [],
    activeFloorId: floor.id,
    outdoorTime: 'day',
    outdoorWeather: 'clear',
    outdoorScenery: 'none',
    planGridSize: PLAN_GRID_DEFAULT,
  }
}

export const FLOOR_MATERIAL_FAMILIES = [
  { id: 'wood', label: '木地板' },
  { id: 'tile', label: '瓷砖' },
  { id: 'marble', label: '大理石' },
  { id: 'grass', label: '草地' },
  { id: 'pool', label: '水池' },
] as const

export type FloorMaterialFamily = (typeof FLOOR_MATERIAL_FAMILIES)[number]['id']

export const FLOOR_MATERIALS: MaterialSwatch[] = [
  // 木地板
  {
    id: 'floor-wood-oak',
    name: '橡木',
    kind: 'floor',
    family: 'wood',
    preview: 'linear-gradient(135deg, #c4a574 0%, #a08050 50%, #c4a574 100%)',
    color: '#b8956a',
    roughness: 0.65,
  },
  {
    id: 'floor-wood-walnut',
    name: '胡桃',
    kind: 'floor',
    family: 'wood',
    preview: 'linear-gradient(135deg, #8b6914 0%, #6b4f3a 50%, #8b6914 100%)',
    color: '#6b4f3a',
    roughness: 0.68,
  },
  {
    id: 'floor-wood-cherry',
    name: '樱桃',
    kind: 'floor',
    family: 'wood',
    preview: 'linear-gradient(135deg, #d4956a 0%, #c97b5a 50%, #d4956a 100%)',
    color: '#c97b5a',
    roughness: 0.62,
  },
  {
    id: 'floor-wood-ash',
    name: '浅灰木',
    kind: 'floor',
    family: 'wood',
    preview: 'linear-gradient(135deg, #e0d4c0 0%, #d4c4a8 50%, #e0d4c0 100%)',
    color: '#d4c4a8',
    roughness: 0.6,
  },
  // 瓷砖
  {
    id: 'floor-tile-white',
    name: '纯白',
    kind: 'floor',
    family: 'tile',
    preview: 'linear-gradient(135deg, #fafafa 0%, #f0f0ee 50%, #fafafa 100%)',
    color: '#f0f0ee',
    roughness: 0.28,
  },
  {
    id: 'floor-tile-gray',
    name: '水泥灰',
    kind: 'floor',
    family: 'tile',
    preview: 'linear-gradient(135deg, #c8c8c8 0%, #b0b0b0 50%, #c8c8c8 100%)',
    color: '#b8b8b8',
    roughness: 0.3,
  },
  {
    id: 'floor-tile-beige',
    name: '米黄',
    kind: 'floor',
    family: 'tile',
    preview: 'linear-gradient(135deg, #f0e8d8 0%, #e8dcc8 50%, #f0e8d8 100%)',
    color: '#e8dcc8',
    roughness: 0.32,
  },
  {
    id: 'floor-tile-slate',
    name: '青灰',
    kind: 'floor',
    family: 'tile',
    preview: 'linear-gradient(135deg, #8a9aa8 0%, #7a8a96 50%, #8a9aa8 100%)',
    color: '#7a8a96',
    roughness: 0.35,
  },
  // 大理石
  {
    id: 'floor-marble-white',
    name: '鱼肚白',
    kind: 'floor',
    family: 'marble',
    preview: 'linear-gradient(135deg, #faf9f7 0%, #f5f3ef 50%, #faf9f7 100%)',
    color: '#f5f3ef',
    roughness: 0.18,
  },
  {
    id: 'floor-marble-gray',
    name: '云灰',
    kind: 'floor',
    family: 'marble',
    preview: 'linear-gradient(135deg, #d8d8d8 0%, #c8c8c8 50%, #d8d8d8 100%)',
    color: '#c8c8c8',
    roughness: 0.2,
  },
  {
    id: 'floor-marble-beige',
    name: '米黄理石',
    kind: 'floor',
    family: 'marble',
    preview: 'linear-gradient(135deg, #e8e0d4 0%, #e0d8cc 50%, #e8e0d4 100%)',
    color: '#e0d8cc',
    roughness: 0.22,
  },
  {
    id: 'floor-marble-dark',
    name: '深灰理石',
    kind: 'floor',
    family: 'marble',
    preview: 'linear-gradient(135deg, #5a5a5a 0%, #3a3a3a 50%, #5a5a5a 100%)',
    color: '#3a3a3a',
    roughness: 0.15,
  },
  // 草地（户外）
  {
    id: 'floor-grass-lawn',
    name: '草坪绿',
    kind: 'floor',
    family: 'grass',
    preview: 'linear-gradient(135deg, #7ec86a 0%, #6aab55 50%, #7ec86a 100%)',
    color: '#6aab55',
    roughness: 0.95,
  },
  {
    id: 'floor-grass-meadow',
    name: '嫩草',
    kind: 'floor',
    family: 'grass',
    preview: 'linear-gradient(135deg, #a5d86a 0%, #8bc34a 50%, #a5d86a 100%)',
    color: '#8bc34a',
    roughness: 0.96,
  },
  {
    id: 'floor-grass-garden',
    name: '深绿',
    kind: 'floor',
    family: 'grass',
    preview: 'linear-gradient(135deg, #5ea048 0%, #4e8b3a 50%, #5ea048 100%)',
    color: '#4e8b3a',
    roughness: 0.94,
  },
  {
    id: 'floor-grass-dry',
    name: '浅黄草',
    kind: 'floor',
    family: 'grass',
    preview: 'linear-gradient(135deg, #b8c878 0%, #a8b86a 50%, #b8c878 100%)',
    color: '#a8b86a',
    roughness: 0.97,
  },
  // 水池
  {
    id: 'floor-pool-blue',
    name: '泳池蓝',
    kind: 'floor',
    family: 'pool',
    preview: 'linear-gradient(135deg, #6ec8e8 0%, #4a9ec8 50%, #3a88b8 100%)',
    color: '#4a9ec8',
    roughness: 0.06,
    metalness: 0.42,
  },
  {
    id: 'floor-pool-deep',
    name: '深水池',
    kind: 'floor',
    family: 'pool',
    preview: 'linear-gradient(135deg, #3a88a8 0%, #2a6888 50%, #1a5878 100%)',
    color: '#2a6888',
    roughness: 0.05,
    metalness: 0.48,
  },
  {
    id: 'floor-pool-light',
    name: '浅水池',
    kind: 'floor',
    family: 'pool',
    preview: 'linear-gradient(135deg, #a8e8f8 0%, #88d8f0 50%, #78c8e8 100%)',
    color: '#78c8e8',
    roughness: 0.08,
    metalness: 0.35,
  },
  {
    id: 'floor-pool-tile',
    name: '池砖',
    kind: 'floor',
    family: 'pool',
    preview: 'linear-gradient(135deg, #58a8c8 0%, #4898b8 50%, #58a8c8 100%)',
    color: '#4898b8',
    roughness: 0.12,
    metalness: 0.38,
  },
]

export function floorMaterialsByFamily(family: FloorMaterialFamily): MaterialSwatch[] {
  return FLOOR_MATERIALS.filter((m) => m.family === family)
}

export function floorMaterialPreviewColor(materialId?: string): string {
  const resolved = materialId ? (LEGACY_FLOOR_MATERIAL_IDS[materialId] ?? materialId) : materialId
  return FLOOR_MATERIALS.find((m) => m.id === resolved)?.color ?? 'rgba(255,255,255,0.08)'
}

/** @deprecated 兼容旧存档 id */
export const LEGACY_FLOOR_MATERIAL_IDS: Record<string, string> = {
  'floor-oak': 'floor-wood-oak',
  'floor-tile': 'floor-marble-white',
  'floor-carpet': 'floor-tile-gray',
}

export const WALL_MATERIALS: MaterialSwatch[] = [
  {
    id: 'wall-white',
    name: '哑光白墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #faf9f7 0%, #f0eeea 100%)',
    color: '#f5f3ef',
    roughness: 0.9,
  },
  {
    id: 'wall-cream',
    name: '奶油白',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #f7f1e6 0%, #ebe3d4 100%)',
    color: '#f0e8da',
    roughness: 0.9,
  },
  {
    id: 'wall-warm',
    name: '暖灰壁纸',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #e8e0d4 0%, #d8d0c4 100%)',
    color: '#e0d8cc',
    roughness: 0.85,
  },
  {
    id: 'wall-beige',
    name: '浅驼墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #e6d7c4 0%, #d4c2ab 100%)',
    color: '#dccab4',
    roughness: 0.88,
  },
  {
    id: 'wall-taupe',
    name: '灰褐墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #cfc6bb 0%, #b8aea2 100%)',
    color: '#c4bab0',
    roughness: 0.86,
  },
  {
    id: 'wall-charcoal',
    name: '深灰墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #6a6a6e 0%, #4e4e52 100%)',
    color: '#5c5c60',
    roughness: 0.82,
  },
  {
    id: 'wall-blue',
    name: '雾蓝墙面',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #d4dde8 0%, #b8c8d8 100%)',
    color: '#c8d4e0',
    roughness: 0.8,
  },
  {
    id: 'wall-sky',
    name: '天空蓝',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #c5d9ea 0%, #a8c4db 100%)',
    color: '#b6cfe0',
    roughness: 0.84,
  },
  {
    id: 'wall-sage',
    name: '鼠尾草绿',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #c8d4c4 0%, #aebcac 100%)',
    color: '#bbc8b6',
    roughness: 0.86,
  },
  {
    id: 'wall-mint',
    name: '薄荷绿',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #cfe8dc 0%, #b4d8c8 100%)',
    color: '#c2dece',
    roughness: 0.85,
  },
  {
    id: 'wall-blush',
    name: '浅粉墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #f0d8d6 0%, #e0c0bc 100%)',
    color: '#e8ccc8',
    roughness: 0.88,
  },
  {
    id: 'wall-lavender',
    name: '淡紫墙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #ddd4e8 0%, #c8bcd8 100%)',
    color: '#d4cae0',
    roughness: 0.84,
  },
  {
    id: 'wall-terracotta',
    name: '陶土橙',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #e0b8a0 0%, #c89878 100%)',
    color: '#d4a888',
    roughness: 0.8,
  },
  {
    id: 'wall-mustard',
    name: '芥末黄',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #e8d4a0 0%, #d4bc78 100%)',
    color: '#dec888',
    roughness: 0.82,
  },
  {
    id: 'wall-clay',
    name: '粘土红',
    kind: 'wall',
    preview: 'linear-gradient(180deg, #c89890 0%, #b07870 100%)',
    color: '#bc8880',
    roughness: 0.84,
  },
]

export const OPENING_STYLES = {
  door: [
    { id: 'door-single', name: '单开门', width: 0.9 },
    { id: 'door-double', name: '双开门', width: 1.6 },
  ],
  window: [
    { id: 'window-standard', name: '标准窗', width: 1.2 },
    { id: 'window-wide', name: '宽窗', width: 1.8 },
  ],
} as const
