import type { HomeBuildDraft, OcPlacement, PlacedFurniture, Vec2, WallSegment } from './types'
import { clampPlanGridSize, PLAN_GRID_DEFAULT } from './defaults'
import { clampWallHeight, resolveFurnitureFloorId } from './scene3dUtils'
import { floorPlanCenter } from './floorPlanGeometry'


const MAX_COORD = 64
const MAX_WALLS = 500

function clamp(n: number, min: number, max: number): number {
  if (!Number.isFinite(n)) return min
  return Math.max(min, Math.min(max, n))
}

function sanitizePoint(p: Vec2): Vec2 {
  return {
    x: clamp(p.x, -MAX_COORD, MAX_COORD),
    z: clamp(p.z, -MAX_COORD, MAX_COORD),
  }
}

/** 旧版把中文路径 encode 进存档，这里解码回来避免 404→方块 */
function sanitizeModelPath(p: string): string {
  if (!p || !/%[0-9A-Fa-f]{2}/.test(p)) return p
  return p
    .split('/')
    .map((seg) => {
      try {
        return decodeURIComponent(seg)
      } catch {
        return seg
      }
    })
    .join('/')
}

function sanitizeFurniture(f: PlacedFurniture, draft: HomeBuildDraft): PlacedFurniture {
  return {
    ...f,
    modelPath: sanitizeModelPath(f.modelPath),
    floorId: resolveFurnitureFloorId(draft, f),
  }
}

function sanitizeWall(w: WallSegment): WallSegment | null {
  const a = sanitizePoint(w.a)
  const b = sanitizePoint(w.b)
  const len = Math.hypot(b.x - a.x, b.z - a.z)
  if (len < 0.05 || len > MAX_COORD * 2) return null
  return {
    ...w,
    a,
    b,
    thickness: clamp(w.thickness || 0.2, 0.1, 0.6),
  }
}

/** 防止异常存档坐标导致自动地板算法卡死 */
export function sanitizeHomeDraft(draft: HomeBuildDraft): HomeBuildDraft {
  return {
    ...draft,
    floors: draft.floors.map((floor) => ({
      ...floor,
      wallHeight: clampWallHeight(floor.wallHeight),
      walls: floor.walls
        .map(sanitizeWall)
        .filter((w): w is WallSegment => w != null)
        .slice(0, MAX_WALLS),
      rooms: floor.rooms
        .filter((r) => {
          const { x, z, w, h } = r.rect
          return (
            Number.isFinite(x) &&
            Number.isFinite(z) &&
            Number.isFinite(w) &&
            Number.isFinite(h) &&
            w > 0 &&
            h > 0 &&
            w <= MAX_COORD &&
            h <= MAX_COORD
          )
        })
        .slice(0, 100)
        .map((r) => ({
          ...r,
          tiles: r.tiles?.slice(0, 800),
        }))
        .filter((r) => !r.autoGenerated),
      floorTileMaterials: Array.isArray(floor.floorTileMaterials)
        ? floor.floorTileMaterials.slice(0, 2000)
        : [],
      wallSegmentMaterials: Array.isArray(floor.wallSegmentMaterials)
        ? floor.wallSegmentMaterials.slice(0, 2000)
        : [],
    })),
    furniture: Array.isArray(draft.furniture)
      ? draft.furniture.slice(0, 500).map((f) => sanitizeFurniture(f, draft))
      : [],
    outdoorTime:
      draft.outdoorTime === 'day' || draft.outdoorTime === 'dusk' || draft.outdoorTime === 'night'
        ? draft.outdoorTime
        : 'day',
    outdoorWeather: (() => {
      const w = draft.outdoorWeather as string | undefined
      if (w === 'thunderstorm') return 'rain'
      if (w === 'clear' || w === 'cloudy' || w === 'rain' || w === 'snow') return w
      return 'clear'
    })(),
    outdoorRainSize: (() => {
      const n = draft.outdoorRainSize
      if (typeof n === 'number' && Number.isFinite(n)) {
        return Math.max(1, Math.min(5, Math.round(n)))
      }
      return (draft.outdoorWeather as string | undefined) === 'thunderstorm' ? 4 : undefined
    })(),
    outdoorRainThunder:
      typeof draft.outdoorRainThunder === 'boolean'
        ? draft.outdoorRainThunder
        : (draft.outdoorWeather as string | undefined) === 'thunderstorm'
          ? true
          : undefined,
    outdoorScenery:
      draft.outdoorScenery === 'none' ||
      draft.outdoorScenery === 'city' ||
      draft.outdoorScenery === 'mountain' ||
      draft.outdoorScenery === 'suburb' ||
      draft.outdoorScenery === 'coast' ||
      draft.outdoorScenery === 'forest' ||
      draft.outdoorScenery === 'field' ||
      draft.outdoorScenery === 'desert'
        ? draft.outdoorScenery
        : 'none',
    outdoorSunAzimuthDay:
      typeof draft.outdoorSunAzimuthDay === 'number' && Number.isFinite(draft.outdoorSunAzimuthDay)
        ? ((draft.outdoorSunAzimuthDay % 360) + 360) % 360
        : undefined,
    outdoorSunAzimuthDusk:
      typeof draft.outdoorSunAzimuthDusk === 'number' && Number.isFinite(draft.outdoorSunAzimuthDusk)
        ? ((draft.outdoorSunAzimuthDusk % 360) + 360) % 360
        : undefined,
    planGridSize: clampPlanGridSize(draft.planGridSize ?? PLAN_GRID_DEFAULT),
    ocPlacement: sanitizeOcPlacement(draft),
  }
}

function sanitizeOcPlacement(draft: HomeBuildDraft): OcPlacement | undefined {
  const floor =
    draft.floors.find((f) => f.id === draft.activeFloorId) ??
    draft.floors.find((f) => f.id === draft.ocPlacement?.floorId) ??
    draft.floors[0]
  if (!floor) return undefined
  const center = floorPlanCenter(floor)
  const raw = draft.ocPlacement
  if (
    raw &&
    Number.isFinite(raw.x) &&
    Number.isFinite(raw.z) &&
    draft.floors.some((f) => f.id === raw.floorId)
  ) {
    return {
      x: clamp(raw.x, -MAX_COORD, MAX_COORD),
      z: clamp(raw.z, -MAX_COORD, MAX_COORD),
      floorId: raw.floorId,
      rotationY: Number.isFinite(raw.rotationY) ? raw.rotationY : 0,
    }
  }
  return { x: center.x, z: center.z, floorId: floor.id, rotationY: 0 }
}
