/** 3D 家园建造 — 数据模型 */

export type HomeBuildMode = 'floorplan' | 'ghost' | 'avatar' | 'walk'

/** 室外时段 */
export type OutdoorTimeOfDay = 'day' | 'dusk' | 'night'

/** 室外天气 */
export type OutdoorWeather = 'clear' | 'cloudy' | 'rain' | 'snow'

export const OUTDOOR_TIME_LABELS: Record<OutdoorTimeOfDay, string> = {
  day: '白天',
  dusk: '傍晚',
  night: '夜晚',
}

export const OUTDOOR_WEATHER_LABELS: Record<OutdoorWeather, string> = {
  clear: '晴天',
  cloudy: '阴天',
  rain: '雨天',
  snow: '下雪',
}

/** 雨滴大小 1–5：越大越密，溅射也越大 */
export const RAIN_SIZE_MIN = 1
export const RAIN_SIZE_MAX = 5
export const RAIN_SIZE_DEFAULT = 3

/** 室外远景背景 */
export type OutdoorScenery =
  | 'none'
  | 'city'
  | 'mountain'
  | 'suburb'
  | 'coast'
  | 'forest'
  | 'field'
  | 'desert'

export const OUTDOOR_SCENERY_LABELS: Record<OutdoorScenery, string> = {
  none: '无背景',
  city: '都市',
  mountain: '山间',
  suburb: '郊区',
  coast: '海滨',
  forest: '森林',
  field: '田野',
  desert: '沙漠',
}

export type FloorPlanTool =
  | 'wall'
  | 'demolish'
  | 'room'
  | 'doorWindow'
  | 'material'
  | 'ceilingHole'

export type GizmoMode = 'move' | 'rotate' | 'scale'

export type RoomType =
  | 'bedroom'
  | 'living'
  | 'kitchen'
  | 'bathroom'
  | 'balcony'
  | 'study'
  | 'other'

export const ROOM_TYPE_LABELS: Record<RoomType, string> = {
  bedroom: '卧室',
  living: '客厅',
  kitchen: '厨房',
  bathroom: '卫生间',
  balcony: '阳台',
  study: '书房',
  other: '其他',
}

export type Vec2 = { x: number; z: number }
export type Vec3 = { x: number; y: number; z: number }

export type WallSegment = {
  id: string
  a: Vec2
  b: Vec2
  thickness: number
}

export type DoorWindowKind = 'door' | 'window'

export type DoorWindowOpening = {
  id: string
  wallId: string
  kind: DoorWindowKind
  /** 0–1 沿墙体 */
  t: number
  width: number
  styleId: string
}

export type RoomZone = {
  id: string
  name: string
  type: RoomType
  /** 矩形区域（米） */
  rect: { x: number; z: number; w: number; h: number }
  /** 1m 地板格子（左下角坐标），用于非矩形封闭区域 */
  tiles?: Vec2[]
  /** 由墙体围合自动生成的地板 */
  autoGenerated?: boolean
  floorMaterialId?: string
  wallMaterialId?: string
}

export type CeilingHole = {
  id: string
  rect: { x: number; z: number; w: number; h: number }
  label: string
}

export type FloorLevel = {
  id: string
  label: string
  walls: WallSegment[]
  rooms: RoomZone[]
  openings: DoorWindowOpening[]
  ceilingHoles: CeilingHole[]
  /** 本层墙体高度（米），缺省为默认 2.8 */
  wallHeight?: number
  /** 单格地板材质（1m 网格坐标） */
  floorTileMaterials?: { x: number; z: number; materialId: string }[]
  /** 墙段材质（沿墙体 0–1 参数，按 1m 分段） */
  wallSegmentMaterials?: { wallId: string; t0: number; t1: number; materialId: string }[]
}

export type PlacedFurniture = {
  id: string
  catalogId: string
  name: string
  modelPath: string
  position: Vec3
  rotation: Vec3
  scale: Vec3
  locked?: boolean
  /** 所属楼层；摆放时写入，用于多层显隐 */
  floorId?: string
}

export type OcPlacement = {
  x: number
  z: number
  floorId: string
  rotationY: number
}

export type HomeBuildDraft = {
  format: 'lumi-home-build-draft'
  version: 1
  characterId: string
  updatedAt: number
  floors: FloorLevel[]
  furniture: PlacedFurniture[]
  activeFloorId: string
  /** 同住 OC 在室内的放置位置（摆放模式可拎起调整） */
  ocPlacement?: OcPlacement
  /** 室外时段（3D 预览） */
  outdoorTime?: OutdoorTimeOfDay
  /** 室外天气（3D 预览） */
  outdoorWeather?: OutdoorWeather
  /** 雨天：雨滴大小 1–5 */
  outdoorRainSize?: number
  /** 雨天：是否打雷 */
  outdoorRainThunder?: boolean
  /** 室外远景（3D 预览） */
  outdoorScenery?: OutdoorScenery
  /** 晴天白天太阳方位角（0–360°，0=北） */
  outdoorSunAzimuthDay?: number
  /** 晴天傍晚太阳方位角（0–360°） */
  outdoorSunAzimuthDusk?: number
  /** 户型 2D 可建造网格边长（米/格），扩建后增大 */
  planGridSize?: number
}

export type CatalogItem = {
  id: string
  name: string
  category: string
  tab: CatalogTab
  modelPath: string
  previewColor?: string
}

export type CatalogTab = 'furniture' | 'lighting' | 'decor' | 'rug' | 'building'

export const CATALOG_TAB_LABELS: Record<CatalogTab, string> = {
  furniture: '家具',
  lighting: '灯具',
  decor: '装饰',
  rug: '地毯挂画',
  building: '建材',
}

export type MaterialSwatch = {
  id: string
  name: string
  kind: 'floor' | 'wall'
  /** 地板材质分类 */
  family?: 'wood' | 'tile' | 'marble' | 'grass' | 'pool'
  /** CSS 背景或纹理预览 */
  preview: string
  /** 3D 材质色 */
  color: string
  roughness?: number
  metalness?: number
}
